language: python
python:
  - "2.7"
cache:
  apt: true
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get update -y
install:
  - sudo chef/run.sh testing
  - pip install -U .
env:  DATABASE_URL=postgres://openaddr:openaddr@localhost/openaddr
script:  python setup.py test
