version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir -p /tmp/P
      - run: cp openaddr/VERSION /tmp/P/FULL
      - run: cut -f1 -d. /tmp/P/FULL > /tmp/P/MAJOR
      - run: docker pull ubuntu:16.04
      - run: docker pull openaddr/prereqs:`cat /tmp/P/MAJOR` || true
      - run: docker build -f Dockerfile-prereqs -t openaddr/prereqs:`cat /tmp/P/MAJOR` .
      - run: docker build -f Dockerfile-machine -t openaddr/machine:`cat /tmp/P/MAJOR` .
      - run: docker save openaddr/prereqs:`cat /tmp/P/MAJOR` | gzip -c --fast > /tmp/P/prereqs.gz
      - run: docker save openaddr/machine:`cat /tmp/P/MAJOR` | gzip -c --fast > /tmp/P/machine.gz
      - persist_to_workspace:
          root: /tmp/P
          paths:
            - FULL
            - MAJOR
            - prereqs.gz
            - machine.gz
  test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/P
      - run: gunzip -c /tmp/P/machine.gz | docker load
      # Postgres needs a little time
      - checkout
      - run: docker-compose up -d && sleep 15
      - run: docker-compose run machine python3 /usr/local/src/openaddr/test.py
  package:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/P
      - run: gunzip -c /tmp/P/prereqs.gz | docker load
      - run: gunzip -c /tmp/P/machine.gz | docker load
      - run: docker tag openaddr/machine:`cat /tmp/P/MAJOR` openaddr/machine:`cat /tmp/P/FULL`
  release:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/P
      - run: gunzip -c /tmp/P/prereqs.gz | docker load
      - run: gunzip -c /tmp/P/machine.gz | docker load
      - run: docker tag openaddr/machine:`cat /tmp/P/MAJOR` openaddr/machine:`cat /tmp/P/FULL`
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push openaddr/prereqs:`cat /tmp/P/MAJOR`
      - run: docker push openaddr/machine:`cat /tmp/P/MAJOR`
      - run: docker push openaddr/machine:`cat /tmp/P/FULL`
workflows:
  version: 2
  everything:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - build
      - release:
          requires:
            - test
            - package
          filters:
            branches:
              only: migurski/upgrade-circleci
