version: 2
jobs:

  # Run tests inside prepared Docker container.
  Test:
    machine: true
    steps:
      - checkout

      # Perform tests, but don't keep images around
      - run: docker build -t machine .
      - run: docker run machine

