version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: cut -f1 -d. openaddr/VERSION > /tmp/MAJOR
      - run: docker pull ubuntu:16.04
      - run: docker pull openaddr/prereqs:`cat /tmp/MAJOR` || true
      - run: docker build -f Dockerfile-prereqs -t openaddr/prereqs:`cat /tmp/MAJOR` .
      - run: docker build -f Dockerfile-machine -t openaddr/machine:`cat /tmp/MAJOR` .
  test:
    machine:
      docker_layer_caching: true
    steps:
      # Postgres needs a little time
      - checkout
      - run: docker-compose up -d && sleep 15
      - run: docker-compose run machine python3 /usr/local/src/openaddr/test.py
  package:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: cut -f1 -d. openaddr/VERSION > /tmp/MAJOR
      - run: docker tag openaddr/machine:`cat /tmp/MAJOR` openaddr/machine:`cat openaddr/VERSION`
  release:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: cut -f1 -d. openaddr/VERSION > /tmp/MAJOR
      - run: docker push openaddr/prereqs:`cat /tmp/MAJOR`
      - run: docker push openaddr/machine:`cat /tmp/MAJOR`
      - run: docker push openaddr/machine:`cat openaddr/VERSION`
workflows:
  version: 2
  everything:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - build
      - release:
          requires:
            - test
            - package
          filters:
            branches:
              only: migurski/upgrade-circleci
